<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/FrontModule/Presenters/templates/@layout.latte */
final class Template_dc1ddcea3b extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" href="/css/styles.css">
	<link rel="icon" type="image/x-icon" href="/images/favicon.ico">
	<title>';
		$this->renderBlock('title', [], function ($s, $type) {
			$ʟ_fi = new LR\FilterInfo($type);
			return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
		}) /* pos 8:9 */;
		echo '</title>
	';
		if ($ʟ_tmp = $this->global->assets->resolve('main.js', [], true)) /* pos 9:2 */ {
			echo $this->global->assets->renderAsset($ʟ_tmp);
		}echo '
</head>

<body>
';
		foreach ($flashes as $flash) /* pos 13:7 */ {
			echo '	<div';
			echo ($ʟ_tmp = array_filter(['flash', $flash->type])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 13:38 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText($flash->message) /* pos 13:68 */;
			echo '</div>
';

		}

		echo "\n";
		$this->renderBlock('content', [], 'html') /* pos 15:2 */;
		echo '</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '13'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
