<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/FrontModule/Presenters/templates/Home/default.latte */
final class Template_c7460d3a69 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'title' => 'blockTitle'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 1:1 */;
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="container">
    <header>
';
		$this->renderBlock('title', get_defined_vars()) /* pos 5:13 */;
		echo '        <p class="subtitle">Automatic generation of commit messages for your project</p>
    </header>

    <div class="endpoints">
        <h2>📋 Available endpoints</h2>

        <div class="endpoint">
            <div>
                <span class="method post">POST</span>
                <span class="path">/api/v1/ai</span>
            </div>
            <p class="description">
                Generates a conventional commit message based on the provided <strong> git diff </strong> result.
            </p>
        </div>

        <div class="endpoint">
            <div>
                <span class="method get">GET</span>
                <span class="path">/api/v1/status</span>
            </div>
            <p class="description">
                Displays info about the API.
            </p>
        </div>

        <div class="endpoint">
            <div>
                <span class="method get">GET</span>
                <span class="path">/api/v1/ping</span>
            </div>
            <p class="description">
                Responds with "Pong!"
            </p>
        </div>
    </div>
    <footer>
        <a href="https://github.com/mxttyseq/commit-generator"><img class="icon" src="/images/github.png" alt="github repo"></a>
        <p class="version">Version 1.0.0</p>
    </footer>
</div>
';
	}


	/** n:block="title" on line 5 */
	public function blockTitle(array $ʟ_args): void
	{
		echo '        <h1>🚀 Commit Generator API</h1>
';
	}
}
